package practicafinal;

import java.awt.image.BufferedImage;
import java.io.File;
import uk.co.caprica.vlcj.component.EmbeddedMediaPlayerComponent;
import uk.co.caprica.vlcj.player.MediaPlayerEventListener;
import uk.co.caprica.vlcj.player.embedded.EmbeddedMediaPlayer;

/**
 * Clase que representa aquella ventanas internas destinadas a la visualización de vídeo
 * @author José Alberto Gómez García modej@correo.ugr.es
 */
public class VentanaInternaVideo extends VentanaInternaSM {

    /**
     * Reproductor de vídeo
     */
    private EmbeddedMediaPlayer vlcplayer = null;
    /**
     * Fichero a reproducir
     */
    private File fMedia;

    /**
     * Creates new form VentanaInternaVideo. Construcor con parámetros
     * @param f Fichero a reproducir
     */
    private VentanaInternaVideo(File f) {
        initComponents();
        fMedia = f;
        EmbeddedMediaPlayerComponent aVisual = new EmbeddedMediaPlayerComponent();
        getContentPane().add(aVisual, java.awt.BorderLayout.CENTER);
        vlcplayer = aVisual.getMediaPlayer();
    }

    /**
     * Método para obtener una instancia de un reproductor de vídeo
     * @param f Fichero a reproducir
     * @return 
     */
    public static VentanaInternaVideo getInstance(File f) {
        VentanaInternaVideo v = new VentanaInternaVideo(f);
        return (v.vlcplayer != null ? v : null);
    }

    /**
     * Método para activar la reproducción
     */
    public void play() {
        if (vlcplayer != null) {
            if (vlcplayer.isPlayable()) {
                //Si se estaba reproduciendo
                vlcplayer.play();
            } else {
                vlcplayer.playMedia(fMedia.getAbsolutePath());
            }
        }
    }

    /**
     * Método para parar la reproducción
     */
    public void stop() {
        if (vlcplayer != null) {
            if (vlcplayer.isPlaying()) {
                vlcplayer.pause();
            } else {
                vlcplayer.stop();
            }
        }
    }
    
    /**
     * Método para realizar una captura sobre el vídeo que se está reproduciendo
     * @param bool Si se debe volcar las figuras en la captura.
     * @return Imagen capturada del vídeo
     */
    @Override
    public BufferedImage getImage(boolean bool){
        return (vlcplayer != null ? vlcplayer.getSnapshot() : null);
    }
    
    /**
     * Método para añadir listeners de eventos del vídeo
     * @param ml 
     */
    public void addMediaPlayerEventListener (MediaPlayerEventListener ml){
        if(vlcplayer != null){
            vlcplayer.addMediaPlayerEventListener(ml);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        setBounds(0, 0, 410, 308);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método para detener la reproducción (de video y sonido) cuando se cierra la ventana
     * @param evt Evento de ventana interna
     */
    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        if(vlcplayer != null) {
            vlcplayer.stop();
            vlcplayer = null;
        }
    }//GEN-LAST:event_formInternalFrameClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
