package SM.JAGG.IU;

import java.awt.Color;

/**
 * Clase para representar los paneles con colores que se mostrarán en los combobox de la interfaz
 * @author José Alberto Gómez García modej@correo.ugr.es
 */
public class PanelColor extends javax.swing.JPanel {

    /**
     * Creates new form PanelColor
     * @param color Color del boton
     */
    public PanelColor(Color color) {
        initComponents();
        botonColor.setBackground(color);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonColor = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(25, 40));
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        botonColor.setPreferredSize(new java.awt.Dimension(25, 25));
        add(botonColor);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonColor;
    // End of variables declaration//GEN-END:variables
}
